-keepattributes Signature
-keepattributes *Annotation*
-keep class com.znliang.committee.data.remote.** { *; }
-keep class com.znliang.committee.domain.model.** { *; }
-dontwarn okhttp3.**
-dontwarn retrofit2.**
